# Generated by Django 5.2.7 on 2025-10-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceanorder',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oceanorder',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='oceanorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='oceanorder',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oceanorder',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
