# Generated by Django 5.2.3 on 2025-11-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0006_oceaninvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oceaninvoice',
            name='due_date',
        ),
    ]
