# Generated by Django 5.2.3 on 2025-11-09 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0007_remove_oceaninvoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceaninvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oceaninvoice',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
