# Generated by Django 5.2.3 on 2025-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0008_oceaninvoice_due_date_oceaninvoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceaninvoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
