# Generated by Django 5.2.3 on 2025-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0009_oceaninvoice_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oceaninvoice',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
