# Generated by Django 5.2.3 on 2025-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0010_remove_oceaninvoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oceaninvoice',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='oceaninvoice',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
