# Generated by Django 5.2.3 on 2025-11-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0011_remove_oceaninvoice_pdf_file_oceaninvoice_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
