# Generated by Django 5.2.3 on 2025-12-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0012_paymenthistory_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceaninvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
