# Generated by Django 5.2.3 on 2025-11-14 07:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0012_paymenthistory_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceaninvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='invoices/'),
        ),
    ]
