# Generated by Django 5.2.3 on 2026-05-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_payments', '0013_oceaninvoice_pdf_file'),
        ('pacific_payments', '0013_oceanorder_line_items_snapshot'),
    ]

    operations = [
    ]
