# Generated by Django 5.2.3 on 2025-12-08 16:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacific_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
